import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { IconContext } from "react-icons/lib/esm/iconContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:h-screen md:overflow-scroll bg-teal-blue-950 bg-opacity-30">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
